### ISSUE TITLE
Move `heap` from in-memory storage to badger key/val

### ISSUE THREAD

**Issue by danmconrad** [figaro-tech/go-fig-db#14]

**Comment by KCraw** [comment]
I’d like to revisit the discussion around interfaces. We use them at other levels to enable easy testing, but are we costing ourselves performance by doing so?

Whatever trade off we decide between testability/performance for hot code paths, we should apply it consistently. 

If we use interfaces, then OrderBook can use the standard heap pkg. If we don’t, we’ve got to some reworking of store and merkle to do. 

We prob need to do some more benchmarking.

**Comment by KCraw** [comment]
Didn’t mean to open and close. 

Did mean to additionally comment that might be worth implementing the easy way and not overoptimizing just yet. That way we get a baseline for tx/sec and can do some real profiling to decide where shaving 500 nanoseconds is worth it... and more importantly, where it isn’t.
