### ISSUE TITLE
Unstable heap data

### ISSUE THREAD

**Issue by KCraw** [figaro-tech/go-fig-db#48]
This is more a topic of discussion than anything else... 

Because of the way the binary heap backing the order min/max heaps works, the backing list of orderbooks is insertion-order dependent. That means that it is possible that OrderA -> OrderB -> OrderC might result in a different backing list, and therefore merkle root, than OrderB -> OrderA -> OrderC. It will always satisfy the property that the same order will be at the top of the list, but the rest of the elements will be insertion-order dependent.

We choose a modified Merkle Patricia trie in part because the same state always results in the same cryptographic fingerprint, independent of insertion order. This remains true, however the same order book market state could generate divergent backing states, which would result in different roots. This can be looked at in one of two ways.

A) This is a problem because it is confusing, and because any set of operations that results in the same end state should have the same root. We don't care if orders are processed in a different sequence, so long as the final result is the same. If so, we will need to use a modified heap sort algorithm, that will almost certainly be less efficient in time complexity than the current implementation. 

B) This is *not* a problem because order processing is inherently order dependent, since a matching engine is included with FigDB. This property adds an extra layer of protection to ensure that not only did we arrive at the same state, but that we got there by processing the same orders in the same sequence (in addition to being able to prove any matched orders were at the top of the book). If so, then there is little reason to keep the price list for price/volume sorted in the database. It might be more efficient to just keep an unsorted array as a single entry, and then sort it in memory when building the ladder.

My initial thought is to favor option B, simply because in the real world order execution will always need to occur in the same sequence to agreement on proper order matching, and speed is important. Thoughts?

**Comment by danielmconrad** [comment]
I'm leaning pretty heavily towards B, but I can also see how, from a data storage standpoint, how things aren't ideal. Besides confusion, are there any repercussions if we don't consider this an issue?

**Comment by KCraw** [comment]
I think there would be repercussions were we not handling order matching; i.e. if we were to just accept orders to insert into a heap for future reference. In that case, the operation wouldn't be order dependent, but the resulting state would be. That would be a big problem, because two instances could disagree on the merkle root despite proper operation.

However, because we are handling order matching, the operation is inherently order dependent, i.e., the order in which orders are processed determines the matching, completely separate from any deterministic state concerns. So even if we used a data structure with a stable backing array, it would have no practical effect, as orders would still need to have a canonical processing order.

Also if we go this route, then we could treat the price list for price/volume data as a btree instead of a sorted array. That would speed it up operations significantly from O(n*log n) to O(log n), but still allow us to iterate through the first N for ladder building.

**Comment by KCraw** [comment]
@danielmconrad if we're in agreement as to approach, then we should consider the following as acceptance criteria for this ticket:

1. Implement `exec/btree` with `BTree` and `Scanner` types for storing sorted data to be accessed sequentially with minimal disk reads
2. Convert the active price list in `exec/orderbook` to make use of `btree` instead of a reverse sorted list

**Comment by KCraw** [comment]
Going to start by submitting a PR to leave the price list unordered, and just sort in memory

**Comment by KCraw** [comment]
Closing this out... will open a new one referencing possible data structures
